apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1 # numbers of pod copies
  selector:
    matchLabels:
      app: backend # linking Deployment and Pod
  template:
    metadata:
      labels:
        app: backend # setup label on the pod
      annotations:
        co.elastic.logs/enabled: "true"
        co.elastic.logs/module: springboot
        co.elastic.logs/json.keys_under_root: "true"
        co.elastic.logs/json.add_error_key: "true"
    spec:
      containers:
        - name: backend
          image: nobugsme/nbank:with_validation_fix
          imagePullPolicy: Always
          ports:
            - containerPort: 4111
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend #сервис будет напрвлять трафик на под у которых app = backend
  ports:
    - name: http
      protocol: TCP
      port: 4111 # порт на сервиса
      targetPort: 4111 # порт на которыыи нужно пересылать
      nodePort: 31934 # по этому порту можно обратиться из вне
  type: NodePort # ClusterIP (он доступен только внутри кластера), NodePort (открывает порт на всех нодах кластера)
