apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenoid
spec:
  replicas: 1 # numbers of pod copies
  selector:
    matchLabels:
      app: selenoid # linking Deployment and Pod
  template:
    metadata:
      labels:
        app: selenoid # setup label on the pod
    spec:
      containers:
        - name: selenoid
          image: aerokube/selenoid:latest
          args: ["-container-network", "nbank-network"]
          ports:
            - containerPort: 4444
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
            - name: selenoid-config
              mountPath: /etc/selenoid
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: selenoid-config
          configMap:
            name: selenoid-config

---
apiVersion: v1
kind: Service
metadata:
  name: selenoid
spec:
  selector:
    app: selenoid #сервис будет напрвлять трафик на под у которых app = selenoid
  ports:
    - protocol: TCP
      port: 4444 # порт на сервиса
      targetPort: 4444 # порт на которыыи нужно пересылать
  type: NodePort
