server=http://localhost:4111
apiVersion=/api/v1/

remote=http://localhost:4444/wd/hub
#baseUrl=http://172.17.16.1:3000
baseUrl=http://host.docker.internal:3000
browserSize=1920x1080
headless=true
browser=chrome

adminName=admin
adminPassword=admin