#base.api.url=http://localhost:4111
base.api.url=http://host.docker.internal:4111
api.version=/api/v1/

#remote=http://localhost:4444/wd/hub
remote=http://host.docker.internal:4444/wd/hub
base.ui.url=http://host.docker.internal:3000
browser.size=1920x1080
headless=true
browser=chrome

admin.name=admin
admin.password=admin