services:
  backend:
    image: nobugsme/nbank:with_validation_fix
    ports:
      - "4111:4111"
    networks:
      - nbank-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4111/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    image: nobugsme/nbank-ui:latest
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - nbank-network
    healthcheck:
      test: ["CMD-SHELL", "cat /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    networks:
      - nbank-network

  selenoid:
    image: aerokube/selenoid:latest
    ports:
      - "4444:4444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/:/etc/selenoid/:ro
    command: ["-container-network", "nbank-network"]
    depends_on:
      - frontend
    networks:
      - nbank-network

  selenoid-ui:
    image: aerokube/selenoid-ui:latest
    ports:
      - "6557:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
    depends_on:
      - selenoid
    networks:
      - nbank-network
networks:
  nbank-network:
    name: nbank-network
