name: Run tests

#trigger
on: [push, workflow_dispatch]

jobs:
  run-tests:
    name: Setup services (review apps) and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository # copy repossitory files into agent runner
        uses: actions/checkout@v6.0.2

      - name: Setup JDK
        uses: actions/setup-java@v5.2.0
        with:
          distribution: "corretto"
          java-version:  "21"

      - name: Setup Maven 3.9.11
        uses: stCarolas/setup-maven@v5.1
        with:
          maven-version: 3.9.11

      - name: Cache maven repo
        uses: actions/cache@v5.0.5
        with:
          path: ~/m2/repository
          key:  ${{runner.os}}-maven-{{hashFiles('**.pom.xml')}}
          restore-keys: |
            ${{runner.os}}-maven-

      - name: Setup services
        run: |
          pwd
          cd ./infra/docker_compose
          ls
          chmod +x ./restart_docker_compose.sh
          ./restart_docker_compose.sh

      - name: Run Api tests
        run: mvn clean test -q -P api

      - name: Run UI tests
        run: mvn clean test -q -P ui